### ISSUE TITLE
Specific word not in dictionary - 2nd April daily

### ISSUE THREAD

**Issue by Staindk** [GroundedGames/hex_words_issues#1]
Not sure if this is the appropriate place to log an issue as small as this - but the following word does not seem to count in today's puzzle:

<details>
<summary>spoiler</summary>

true
</details>

**Comment by GroundedGames** [comment]
This works just fine - I'd be lucky if all my issues are this small!

Looks like "true" and "false" are in the dictionary we use but for some reason they're in all caps. Not sure why that's the case, but it's fixed now. 

It usually takes a couple days for the Play Store to approve/publish updates, so I'll leave this open until the fix is fully published. Thanks for reporting it :)

**Comment by Staindk** [comment]
Awesome, glad it was something as simple as that.

Cool game btw :)
